# ==============================================================
# CONFIGURAÇÃO DE BANCO DE DADOS (DML - ACESSO RESTRITO)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_homolog
spring.datasource.username=wallet_api_homolog
spring.datasource.password=api123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# ACTUATOR HEALTHCHECK (Monitoramento SecOps)
# ==============================================================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never